spring:
  application:
    name: zuul-api-gateway

server:
  port: 8661


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  ignored-services: '*'
  routes:
    user-authentication:
      path: /users/**
      serviceId: user-authentication
      stripPrefix: true
      sensitiveHeaders:
    public-forum:
      path: /forum/**
      serviceId: public-forum
      stripPrefix: true
      sensitiveHeaders:

